### ISSUE TITLE
Integrate with autoplot?

### ISSUE THREAD

**Issue by krlmlr** [dewittpe/qwraps#8]
See https://github.com/hadley/ggplot2/wiki/autoplot. The general idea is:
- Provide a generic `fortify` method for the data
- Provide a generic `autoplot` method that uses the fortified data to produce something sensible

Would you be interested?

**Comment by dewittpe** [comment]
`qwarps` has been deprecated.  Please see [qwraps2](https://github.com/dewittpe/qwraps2).

However, the idea of an autoplot is interesting.  The implementation for functions such as `qroc` and `qkmplot` within the [qwraps2](https://github.com/dewittpe/qwraps2) package seem to implicitly use a `fortify` methods.   Work could be done to generalize the methods.

However, I think the use of `ggproto` in `ggplot2_2.0.0` would be better tool to use in `qwraps2`.
